### ISSUE TITLE
Support community version kubernetes milestone 

### ISSUE THREAD

**Issue by barnettZQG** [goodrain/rainbond-install#174]
## about docker.(default install docker 17.04.x branch) 
- [ ] set container logger driver:
   - [ ] manager node set logger driver is `json-file`、`max-size=50M`、`max-file =2`
   - [ ] compute node set logger driver is `json-file`、`max-size=20M`、`max-file =2`
## about kubernetes.(default install kubernetes 1.10)
- [ ] add default namespace `rainbond` after install kubenetes
